version: "3"
services:
  mariadb:
    build: ./mariadb
    container_name: app_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: app_db
      MYSQL_USER: hoge
      MYSQL_PASSWORD: hogehoge
    volumes:
      - ./mariadb/db:/docker-entrypoint-initdb.d

  api:
    build: ./java
    container_name: app_api
    volumes:
      - ./java/api:/app
    ports:
      - 8000:8000
    command:
      - sh
    tty: true

  react:
    image: nginx:latest
    container_name: app_server
    volumes:
      - ./react/dist/:/usr/share/nginx/html/
    ports:
      - 8801:80
